services:
  db:
    image: postgres:15-alpine
    container_name: channel_db_2
    environment:
      POSTGRES_DB: channel_db
      POSTGRES_USER: channel_user_2
      POSTGRES_PASSWORD: channel_pass123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: channel_web_2
    command: >
      sh -c "
        echo 'Ждем базу данных...' &&
        sleep 5 &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 core.wsgi:application
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-this}
      - DEBUG=False
      - DATABASES_NAME=channel_db
      - DATABASES_USER=channel_user_2
      - DATABASES_PASSWORD=channel_pass123
      - DATABASES_HOST=db
      - DATABASES_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1 # ваш-домен.com
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: channel_nginx_2
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
#      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: